### ISSUE TITLE
Shipswitcher issues

### ISSUE THREAD

**Issue by twisting2017** [perryhuynh/kcauto#108]
*Please read the FAQ section of the kcauto-kai Wiki before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto-kai version 0.4.0
* Viewer/browser: kc3
* Operating system: windows 10

#### Issue variability
consistent
#### Issue

 * When sparkling, ShipSwitcher will no longer re-visit previously checked ships
 * When sparkling, ShipSwitcher will disable the Combat module if there are no more potential ships to switch to, avoiding infinite sorties with the last ship

those 2 functions arent working, shipswitcher will always check every ship that fits the criteria defined, going through all pages every time. when no ship is found by the end of the list, sorties will continue.

#### Log (if applicable)
```
[insert ~50 lines of console log here]
```

#### Config (if applicable)
```
**# config automatically generated from kcauto-kai frontend (v0.4.1)

[General]
Program: Chrome
JSTOffset: -8
Pause: False

[ScheduledSleep]
SleepEnabled: True
SleepStartTime: 0000
SleepLength: 4
ExpeditionSleepEnabled: False
ExpeditionSleepStartTime: 0000
ExpeditionSleepLength: 3
CombatSleepEnabled: False
CombatSleepStartTime: 0000
CombatSleepLength: 5

[Expeditions]
Enabled: True
Fleet2: 2
Fleet3: 6
Fleet4: 5

[PvP]
Enabled: False

[Combat]
Enabled: True
Engine: legacy
Map: 1-1
FleetMode: 
CombatNodes: 
NodeSelects: 
Formations: 
NightBattles: 
RetreatLimit: heavy
RepairLimit: moderate
RepairTimeLimit: 2355
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: 

[ShipSwitcher]
Enabled: True
Slot1Criteria: damage,sparkle
Slot1Ships: C:AV:>40:_:_,C:CA:>40:_:_,C:CAV:>40:_:_,C:CL:>40:_:_,C:CLT:>40:_:_,C:CV:>40:_:_,C:CVB:>40:_:_,C:CVL:>40:_:_,C:DD:>40:_:_
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: False**
```

**Comment by mrmin123** [comment]
@twisting2017 just looked at your config. The two ShipSwitcher behavior is *only* valid for ships specified via Position, not Class.

**Comment by mrmin123** [comment]
The two noted ShipSwitcher behavior cannot be replicated when switching by asset, not position, since kcauto-kai cannot maintain an internal list of individual list of ships just from the asset matches. I do have an idea to update the cached page if none of the potential ships on the page are valid ONLY if it's on sparkle mode, since this would not be desirable for something like Orel. This would still mean that the script would check every ship for sparkle on the page it jumps to, but at least it wouldn't jump to a page that is known to have no available (non-sparkled) ships previously.
