### ISSUE TITLE
How to use Pause?

### ISSUE THREAD

**Issue by mintgreenrose** [perryhuynh/kcauto#143]
Really sorry for the seemingly stupid question but I've searched and found no answer to how to use it. does it allow me to pause the script temporarily to, let's say, scrap unwanted ships? before resuming 3-2A runs? Or does it work like a delay to restore fatigue levels only? Thanks

**Comment by waicool20** [comment]
If the script is running and you change the config `Pause` to `True` then it will pause on the next cycle. Conversely if it's set to `False` then it will the script will continue after a few seconds.

**Comment by mintgreenrose** [comment]
Thanks, I think I have an idea now how it works

**Comment by mrmin123** [comment]
To further clarify, this works simply by utilizing the config hot reload capability. If kcauto-kai is already running, and you modify the config file to set `Pause` to `True` *while* the script is still running, the script will hot-reload the config on the next cycle (~15s after the last time the stats have been printed), see that the `Pause` line has been set, and pause the script to let you do stuff in-game without having to stop the script out-right. While the script is paused, it is still checking for updates to the config file in the background, so once you're done you can update the config file to set `Pause` to `False` and the script will resume.

Due to the nature of the automation profile the safest times to actually intervene and modify the config file is during combat (when a battle is underway), pvp (when a battle is underway), or when the script is idling to begin with. Unless the script is idling to begin with, kcauto-kai will finish the entire in-progress cycle before re-loading the config.

I plan on writing up some documentations this weekend but this is basically it for the Pause feature.
