### ISSUE TITLE
[Feature Request] Allow dynamic setting of force retreat nodes

### ISSUE THREAD

**Issue by sakura-quest** [perryhuynh/kcauto#156]
In maps such as 4-3 for DD/CL/DE grinding, where routing is random, I want to be able to do variable number of  battles. For example, if I get sent to node J first, I want to perform 3 battles (nodes J->F->K or nodes J->F->D. However, if I get sent to node F first, I want to perform 2 battles (nodes F->K or F->D). One way to implement this in a flexible manner that I see would be to allow users to specify custom retreat nodes. Currently, there are some nodes statically defined as retreat nodes in the various maps.json files (e.g. 2-4 node C). If users are able to specify custom retreat nodes, then they will be able to vary the number of battles based on the route their fleet took. 

For example, in the 4-3 case above, I would say that the CombatNodes value is 3 (meaning maximum of 3 battles), but set custom retreat nodes as K and D, so that even if I skipped node J, I would still end my sortie at nodes K and D.

**Comment by perryhuynh** [comment]
You can already specify to retreat by adding `"types": ["retreat"]` to whatever nodes you want in the the 4-3 map JSON file though

**Comment by sakura-quest** [comment]
I just thought that being able to specify it via the config.ini (and having support for it in the browser config generator) would be more user friendly, especially since the ability to specify `"types": ["retreat"]` in the map json file is only something a user would know by reading the code.

**Comment by sakura-quest** [comment]
Also, I felt that the map.json file is something more akin to a resource file for the program, that a user should not touch. If a user modifies the map.json file, then they have to remember to revert it back since otherwise it can cause issues for their future sorties, if they do not want the behavior anymore. It would be easier on them if all they had to change was the config.ini file which they are expected to do anyways.

**Comment by perryhuynh** [comment]
Ah yeah mrmin did note he would explore allowing users to specify their own retreat nodes at the config level but this was about 4 or 5 months ago

**Comment by mrmin123** [comment]
Users shouldn't be afraid to change the map JSON files but I admit that it's a bit unwieldy if you're not familiar with JSON, and it's not documented at the moment. That said, I'm not sure if I like the implementation in #160.

It's not wrong, and it's a step in the right direction (moving it to the config), but it's the naive solution: it's adding Combat config option that is only relevant to one of the combat engine modes (notice that all other options can be engine-agnostic). and a conceptually identical config options (that works for both combat engines) exists in the form of `CombatNodes`.

The option I was considering a while back was merging the retreat node specification and the combat node count options together, since they ostensibly do the same thing. So in your case this new merged config (let's call it `RetreatNodes` as an example) the line would be `RetreatNodes: 3, D, K`.

There would have to be additional checks on both the webUI and the config loader to verify that there is only one integer 'node' specified (the combat node count), but I think this would consolidate the two options both conceptually and by lines in the config.

**Comment by sakura-quest** [comment]
What you say makes sense. The purpose of retreat nodes and combat node count is the same, so combining them to the same config makes sense. However, I'm not sure what the best way would be to phrase this combined option in the config generator UI. Would something like "Max battle count/retreat Nodes..." be clear enough? 

Also, I am a bit unclear on what the different engine options are, as I have admittedly only used the live engine mode. In the legacy engine case, would I have to update the fleet position by calling `CombatModule._update_fleet_position_once` again at some point, and if so, what I would I do in the case that the compass covers the current node? 

I'd be willing to make changes as necessary to get this feature in, though I might not be able to get to it till the weekend.

**Comment by mrmin123** [comment]
I think that label works, but as 'Max Battle Count/Retreat Nodes' for consistent capitalization, and it can replace the 'Combat Node Count' dropdown. It would have to be a multiselect now, and the options would also need to include the Node names.

As for live vs legacy, there's a brief outline of the differences in the [wiki](https://github.com/mrmin123/kcauto-kai/wiki/Config:-Combat-section#engine). If the user supplies named nodes and they're using the legacy engine, the named node selections will have to be ignored as the legacy engine is not capable of knowing what node the fleet is at, and only use the numeric value passed in (if a numeric value is passed in) to determine the retreat.

No worries on the timing, since this is more of a nice-to-have, and the base functionality already exists in the codebase, albeit in a form more difficult to get to.
