### ISSUE TITLE
[Feature Request] Entering <Node> Trigger Stop KCauto

### ISSUE THREAD

**Issue by nekoma0** [perryhuynh/kcauto#190]
Feature Request : Prevent/Stop/Kill KCauto from running when entering unintended node. (if possible, include a popup sound or something to notify user when this triggered)

Sometimes, users such as myself tends to screw up when configuring our fleet, and enable kcauto without knowing that there's a mistake in fleet configuration, such as not enough LoS(Line of Sight), or incorrect fleet composition that leads to unintended node.

And these might leads to unintended waste of resources, and too late for the user get noticed.

**Comment by mrmin123** [comment]
So you basically want a more dramatic version of `RetreatNodes`? One that kills the script, instead of simply retreating?

I personally don't know if such a feature is in line with the operational and design assumption kcauto makes, which is that the onus is on the user to make sure that both the config and in-game setups are correct. How would the script ascertain what is a 'bad' node? Via config? That means that the onus is *still* on the user to specify the bad nodes via the config. Via the map json files? That makes it difficult for different routes, compositions, strats, etc...

This is not to say it's not possible, but I have my reservations about adding it as a feature.

(Unless this is actually a feature desired by many people)

If you really wanted to patch this in in place of `RetreatNodes`, you could change the `resolve_continue_sortie()` method within `mapData.py` to this:
```python
        import sys
        if node:
            if (node.name in self.config.combat['retreat_nodes'] or
                    'retreat' in node.types):
                sys.exit(1)
        return True
```
This will forcibly stop the script if the script encounters a node specified in the `RetreatNodes` field. Only compatible with the Live Combat engine.

**Comment by nekoma0** [comment]
thanks, i will use the modified portion that you provided.
Personally i don`t think this feature will be desired by many people thou, so i will just make use of the retreat node, since i always set run kcauto and then went out for work or something, so i never check them if they were running smoothly before going out.

For this feature, in certain world/maps, there's certain few certain nodes or dead end that we would want to avoid/prevent waste resources since it's going to fail infinitely.(unless that dead end node specifically have ship drops that user wanted)
So this feature is sort of like a "fail-safe" just in case of user-error.

let's say, a example.
World 2-5
And i choose the north route which is A-D-H-L.
if my configuration is perfect and complete, the route will be perfectly A-D-H-L.

But when i did screw up in configuring the fleet, be it wrong ship composition or not enough los, causing the fleet to go to the route that i didn't plan them for.
With Fail-safe feature that stop battle/stop kcauto, adding Node C , G, J will trigger fail-safe, and stop it from wasting resources further.
