### ISSUE TITLE
Use clear medal on sortie panel for ClearStop

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#194]
![](https://cdn.discordapp.com/attachments/370233436327247874/462702039026368522/unknown.png)

The `ClearStop` option should look for the clear medal on the top right of the sortie panel rather than the medal that appears in the results screen. Currently the `ClearStop` option doesn't seem to be working 100% of the time so I believe looking for this would be better since there is currently only one chance to look for the medal.

**Comment by mrmin123** [comment]
As much as I'd like to incorporate this, there are some challenges associated which I haven't figured out how to resolve yet:

* The search space -- the panel images right now are of varying dimensions due to the medal, possible progress bars, and overlap with the EO arrows. The varying dimensions make dynamic resizing of the search space difficult
  * Possible solution: define fixed search spaces for each of the 4 standard map panel and 3 EO map panel locations. Search spaces for Events would potentially have to be re-defined for each event (minor to moderate inconvenience)
* The asset match -- standard maps (including EOs) all share the same medal image. Event maps have 4 different possible medal images based on difficulty. In addition, these medal images are often occluded by the EO arrow (for standard maps) or the next page arrow(s) (for Event maps), often to the point of being unable to see the said medal.
  * Possible solution: ??? Just document and let users know about the limitation??? Maybe not a big deal because most of the time ClearStop is being used for EOs???

Any feedback or thoughts welcome.
