### ISSUE TITLE
Repair 2nd fleet flagship in combined fleet at moderate damage regardless of config

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#286]
You cannot sortie a combined fleet without the flagship of the 2nd being at minor damage or above so it needs to be repaired regardless of the specified `RepairLimit` for cases where it is set as `heavy`

**Comment by mrmin123** [comment]
Are you saying that the flagship of the second fleet must be at minor
damage or scratch/no damage otherwise the game doesn't let you sortie the
combined fleet? And if at moderate or heavy the game will does not let you
sortie outright?

**Comment by perryhuynh** [comment]
Yes

EDIT:
`You can't begin a sortie with the escort fleet flagship moderately damaged.`

Source: http://kancolle.wikia.com/wiki/Combat/Combined_Fleet

**Comment by mrmin123** [comment]
I'm away from the desk right now, but b off the top of my head, I don't
know if there is an easy way around this. I don't think here is an asset
the script can use to identify the second fleets flagship in the repair
list since the fleet marker is the same for all ships in the second fleet.
You might have to resort to using a repair cut off of moderate when using a
combined fleet.

**Comment by perryhuynh** [comment]
Hmm yeah it seems better to just leave this as a won't fix for now
