### ISSUE TITLE
Add support for usage of Emergency Repair Personnel/Goddess for flagship

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#291]
In addition to the ability to actually utilize the Emergency Repair Personnel/Goddess, it allows for the new method of farming ammo in World 3-2.

This image can be used to generate the asset for usage of Emergency Repair Personnel/Goddess on a flagship.
![emergencyrepair](https://user-images.githubusercontent.com/9361780/45922982-31817000-be8e-11e8-9999-4f57ca549191.png)

**Comment by mrmin123** [comment]
I will not be supporting this in kcauto unless there is overwhelming support for it. These are purchasable items that I do not want kcauto to automate around. My mentality is that if you are sending Emergency Repair out with your fleet, you should be supervising it in the first place, especially since kcauto has no ability to replenish used Emergency Repairs on the fleet.

I don't know what the ammo farming method on 3-2 entails to require Emergency Repair support, but I'm guessing the farm loop is broken if you can't replenish the Emergency Repair.

**Comment by perryhuynh** [comment]
![image](https://user-images.githubusercontent.com/9361780/45923045-dbadc780-be8f-11e8-856c-0705d9def11b.png)
The method involves going from node A>B and using one ship with a repair team on it, which allows the ship to continue onto the node instead of being force retreated if met with a taiha. The repair team is never actually used with this farming method.

**Comment by mrmin123** [comment]
So in the above farming scenario, which button is actually pressed in the first screenshot?

**Comment by perryhuynh** [comment]
It doesn't matter in this scenario, either works I just thought if you were to implement this you would want to have the option to use either, the above buttons only pop up if using it on the flagship

**Comment by mrmin123** [comment]
I'm still going to push back on this. Emergency Repair opens up kcauto to a level of user confusion regarding its behavior (restocking, Goddess vs Personnel) and potential tangential feature requests (restocking, equipment interaction in general, Goddess vs Personnel, 'smart' Emergency Repair usage, etc) that I'd much rather not have to deal with.
