### ISSUE TITLE
Ship Counter OCR Issues with non-Windows Systems

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#328]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 7.0.0
* Viewer/browser: Chromium
* Operating system and/or VM: Xubuntu 16.04

#### Issue variability
Consistent

#### Issue
Due to differences in font rendering across different operating systems, the ship counter in the top part of the UI which is used for repair/ship switcher/etc is not in the same same leading to errors in OCR. I've included some screenshots below to show where the `ship_counter` region is highlighted with a default install of `Xubuntu 16.04`. Is there any feasible way to handle this issue? I've tried redefining the `ship_counter` region on my own and that has solved the issues at least for a specific UI.
 
UI 1:
![image](https://user-images.githubusercontent.com/9361780/49480481-b4eb0600-f7db-11e8-8c1a-dc3c1e0fd4fc.png)

UI 2:
![image](https://user-images.githubusercontent.com/9361780/49480495-bf0d0480-f7db-11e8-8639-17e490445251.png)

UI 3:
![image](https://user-images.githubusercontent.com/9361780/49480503-c502e580-f7db-11e8-9bd6-73ac73358713.png)

UI 4:
![image](https://user-images.githubusercontent.com/9361780/49480516-caf8c680-f7db-11e8-8479-0b8cf48f7001.png)

UI 5:
![image](https://user-images.githubusercontent.com/9361780/49480520-cfbd7a80-f7db-11e8-80a5-aeaf749ff897.png)

**Comment by mrmin123** [comment]
This is less of a cross-OS font rendering issue and more of a UI issue. As
much as it irks me, kcauto will need to be modified to recognize which UI
is being used and modify the `ship_counter` region accordingly. Previously
I recommended that UIs 4 and 5 be used (the font/background color
combination causes issues on the metal UIs) but I have to modify my
recommendation to using UI 4 only since UI 5 moves things around again.

Thanks,
- Min
