### ISSUE TITLE
2019 Spring Event Support

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/kcauto#357]
The 2019 Spring Event *should* be starting today

**Comment by mrmin123** [comment]
Ongoing event-related updates will be in the branch [357-2019-spring-event](https://github.com/mrmin123/kcauto/tree/357-2019-spring-event).

To checkout this branch from the command line:
```
git fetch
git checkout 357-2019-spring-event
```

**Comment by mrmin123** [comment]
Branch has been updated with updated JSON node data and panel images.

**Comment by tsuki-tsuki** [comment]
This is happening when I tried sortieing to E2 using kcauto

`Sortie complete. Encountered 4 combat nodes (nodes N, O3, P3, P3).[0m`

Why did P3 detected twice? I’m running using java11, so maybe it relates to java version?

**Comment by mrmin123** [comment]
@tsuki-tsuki this is typically due to the nodes being so close to each other and the script can't consistently tell which node you are at by the icon. You can override the formation/night battle selections for the 4th node by specifying by them combat node number instead of node name, so something like `4:line_ahead` as opposed to `Q3:line_ahead`.

**Comment by tsuki-tsuki** [comment]
I see, thank you for the verification! By the way, when will data for E4+ will be updated? Just asking

**Comment by mrmin123** [comment]
I'll add that info either tonight or tomorrow night.

**Comment by mrmin123** [comment]
Data for E-4 and E-5 have been added to the `357-2019-spring-event` branch.
