### ISSUE TITLE
Add support for retreat nodes and alt node coords within node dict in json

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#49]
For live combat engine.

**Comment by n0k0m3** [comment]
2-4 C (actually 2-4 B but we don't have the F5 retreat feature yet and it's still nice to have some extra rsc)
3-5 E (for once in a blue moon)
3-1 A (thanks @twisting#0228 on discord)

Nice to have (but doesn't matter much because of...):
1-3 E (weak enemy)
1-5 D (continuing = dead end node, still nice to have but doesn't make a difference)
1-6 L (no one takes this route if they use standard guided compo)
4-1 H (ppl who want to clear the map should use the suggested compo and read guides)
5-5 B (no one takes this route though)

**Comment by perryhuynh** [comment]
I would advise against ever implementing the F5 retreat feature, that's asking for a ban
