### ISSUE TITLE
Sleep Algorithm Question 

### ISSUE THREAD

**Issue by yhn147** [perryhuynh/kcauto#92]
I used a translator. Please excuse.

In Orel process or other process, The repair docks are empty, there's a replacement submarines.
but process sleep 1 hour in expedition screen. Of course Scheduled Sleep is false.

5 cycle and 1 hour break, n cycle 1 hour break..
I think the program has more sleep time than I think.

By what standards does the resting process work? 
Can I change this break time or frequency?

By using a translator, this issue could look offensive. But please forgive me for I have no such intention. I would like you to accept it as either a just question or a suggestion.

**Comment by mrmin123** [comment]
Could you clarify what you mean by 'expedition screen'?

It sounds like you're Orel cruising with the script; there's an issue with ending on resource nodes which is addressed in the `staging` branch, but it would simply crash instead of sleeping for an hour. The only reason it would sleep for that long is if a ship in the fleet is being repaired and no adequate replacement ship is found. In this case, the sleep time would be for the length of the repair timer.
