### ISSUE TITLE
lbas.py module looks for wrong image for event lbas resupply faded menu. 

### ISSUE THREAD

**Issue by ptv999duke** [perryhuynh/kcauto#98]
the lbas.py module looks for the image file 'lbas_resupply_menu_button_event_faded
.png'. However, the image file under that folder is named 'lbas_resupply_menu_button_faded_event.png'

**Comment by waicool20** [comment]
Check your kca kai installation, there in fact is a file named `lbas_resupply_menu_button_event_faded
.png`.

https://github.com/mrmin123/kcauto-kai/blob/master/kcauto-kai.sikuli/combat.sikuli/lbas_resupply_menu_button_faded.png

btw use backticks ` (The key with ~) instead of quotes ( ' ) to put things in code blocks

**Comment by ptv999duke** [comment]
Thanks for the tip. 
The image you linked is `lbas_resupply_menu_button_faded` which is not the event one. This issue is specifically for the lbas resupply faded button for events.

**Comment by perryhuynh** [comment]
This issue was fixed a long time ago, please use the latest version

**Comment by perryhuynh** [comment]
Issue is already fixed in the `64-event-2018-winter` branch

**Comment by ptv999duke** [comment]
Thanks for letting me know of the branch that this is fixed in. I'll pull the upstream changes from that branch. 

Sorry for not closing the PR and issue earlier today. Was busy throughout the day and night,

**Comment by mrmin123** [comment]
No worries, I had forgotten that this was an addressed issue.
